const courses = [
  {
    title: "Programming Laravel 0",
    detail: "(Getting Started with Laravel 9)",
    batch: "September 2022",
    mentor: "William Hartono, Farel Prayoga",
    oldPrice: "Rp 2060.000",
    newPrice: "Rp 560.000",
  },
  {
    title: "Programming 1",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 2",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 3",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 4",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 5",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Component Nomor ke-6",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 7",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 8",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 9",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 10",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Programming 11",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
  {
    title: "Nomor ke-12",
    detail: "(Getting Started with C)",
    batch: "September 2023",
    mentor: "Andrew",
    oldPrice: "Rp 2010.000",
    newPrice: "Rp 510.000",
  },
];


export {courses}